/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JFrame;

import modelo.ArbolGeneradorPuzzle;
import modelo.Puzzle;

/**
 * 
 * @author naty
 */
public class GUI_Puzzle extends javax.swing.JFrame {

	private ArbolGeneradorPuzzle arbol;

	/**
	 * Creates new form GUI_Puzzle
	 */
	public GUI_Puzzle() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel9 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLayeredPane2 = new javax.swing.JLayeredPane();
		I1 = new javax.swing.JTextField();
		I4 = new javax.swing.JTextField();
		I7 = new javax.swing.JTextField();
		I2 = new javax.swing.JTextField();
		I5 = new javax.swing.JTextField();
		I8 = new javax.swing.JTextField();
		I3 = new javax.swing.JTextField();
		I9 = new javax.swing.JTextField();
		I6 = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jLayeredPane1 = new javax.swing.JLayeredPane();
		S1 = new javax.swing.JTextField();
		S4 = new javax.swing.JTextField();
		S7 = new javax.swing.JTextField();
		S2 = new javax.swing.JTextField();
		S5 = new javax.swing.JTextField();
		S8 = new javax.swing.JTextField();
		S3 = new javax.swing.JTextField();
		S9 = new javax.swing.JTextField();
		S6 = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		pesoAlpha = new javax.swing.JTextField();
		jLabel11 = new javax.swing.JLabel();
		generarArbol1 = new javax.swing.JButton();
		opcion = new javax.swing.JComboBox<>();
		Ptxt = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		Pjtext = new javax.swing.JTextField();
		Qjtext = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		caminojtext = new javax.swing.JTextField();
		arbolbtn = new javax.swing.JButton();
		etiquetaSol = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		getContentPane().setLayout(
				new org.netbeans.lib.awtextra.AbsoluteLayout());

		jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
		jLabel9.setText("PUZZLE");
		getContentPane().add(
				jLabel9,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 6, -1,
						-1));

		jLabel6.setText("ALGORITMO BEST FIRST (A)");
		getContentPane().add(
				jLabel6,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 42, -1,
						-1));

		jLayeredPane2.setBorder(javax.swing.BorderFactory
				.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

		I1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
		I1.setAlignmentX(1.0F);
		I1.setAlignmentY(1.0F);
		I1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				I1ActionPerformed(evt);
			}
		});
		I1.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				I1KeyTyped(evt);
			}
		});

		I4.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
		I4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				I4ActionPerformed(evt);
			}
		});
		I4.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				I4KeyTyped(evt);
			}
		});

		I7.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
		I7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				I7ActionPerformed(evt);
			}
		});
		I7.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				I7KeyTyped(evt);
			}
		});

		I2.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
		I2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				I2ActionPerformed(evt);
			}
		});
		I2.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				I2KeyTyped(evt);
			}
		});

		I5.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
		I5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				I5ActionPerformed(evt);
			}
		});
		I5.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				I5KeyTyped(evt);
			}
		});

		I8.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
		I8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				I8ActionPerformed(evt);
			}
		});
		I8.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				I8KeyTyped(evt);
			}
		});

		I3.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
		I3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				I3ActionPerformed(evt);
			}
		});
		I3.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				I3KeyTyped(evt);
			}
		});

		I9.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
		I9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				I9ActionPerformed(evt);
			}
		});
		I9.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				I9KeyTyped(evt);
			}
		});

		I6.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
		I6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				I6ActionPerformed(evt);
			}
		});
		I6.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				I6KeyTyped(evt);
			}
		});

		jLayeredPane2.setLayer(I1, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane2.setLayer(I4, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane2.setLayer(I7, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane2.setLayer(I2, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane2.setLayer(I5, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane2.setLayer(I8, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane2.setLayer(I3, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane2.setLayer(I9, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane2.setLayer(I6, javax.swing.JLayeredPane.DEFAULT_LAYER);

		javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(
				jLayeredPane2);
		jLayeredPane2.setLayout(jLayeredPane2Layout);
		jLayeredPane2Layout
				.setHorizontalGroup(jLayeredPane2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jLayeredPane2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jLayeredPane2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jLayeredPane2Layout
																		.createSequentialGroup()
																		.addComponent(
																				I1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				60,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				I2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				60,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				I3,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				60,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jLayeredPane2Layout
																		.createSequentialGroup()
																		.addGroup(
																				jLayeredPane2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								I4,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								60,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								I7,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								60,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGroup(
																				jLayeredPane2Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jLayeredPane2Layout
																										.createSequentialGroup()
																										.addGap(12,
																												12,
																												12)
																										.addComponent(
																												I8,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												60,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addComponent(
																												I9,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												60,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGroup(
																								jLayeredPane2Layout
																										.createSequentialGroup()
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addComponent(
																												I5,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												60,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(12,
																												12,
																												12)
																										.addComponent(
																												I6,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												60,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		jLayeredPane2Layout
				.setVerticalGroup(jLayeredPane2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jLayeredPane2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jLayeredPane2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																I1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																60,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																I2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																60,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																I3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																60,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												jLayeredPane2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																I4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																60,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																I5,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																60,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																I6,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																60,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												jLayeredPane2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																I7,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																60,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																I8,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																60,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																I9,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																60,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		getContentPane().add(
				jLayeredPane2,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 156, -1,
						-1));

		jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
		jLabel2.setText("Solución");
		getContentPane().add(
				jLabel2,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 108, -1,
						-1));

		jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
		jLabel1.setText("Estado inicial");
		getContentPane().add(
				jLabel1,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 108, -1,
						-1));

		jLayeredPane1.setBorder(javax.swing.BorderFactory
				.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

		S1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
		S1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				S1ActionPerformed(evt);
			}
		});
		S1.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				S1KeyTyped(evt);
			}
		});

		S4.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
		S4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				S4ActionPerformed(evt);
			}
		});

		S7.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
		S7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				S7ActionPerformed(evt);
			}
		});

		S2.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
		S2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				S2ActionPerformed(evt);
			}
		});

		S5.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
		S5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				S5ActionPerformed(evt);
			}
		});

		S8.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
		S8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				S8ActionPerformed(evt);
			}
		});

		S3.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
		S3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				S3ActionPerformed(evt);
			}
		});

		S9.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
		S9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				S9ActionPerformed(evt);
			}
		});

		S6.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
		S6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				S6ActionPerformed(evt);
			}
		});

		jLayeredPane1.setLayer(S1, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane1.setLayer(S4, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane1.setLayer(S7, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane1.setLayer(S2, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane1.setLayer(S5, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane1.setLayer(S8, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane1.setLayer(S3, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane1.setLayer(S9, javax.swing.JLayeredPane.DEFAULT_LAYER);
		jLayeredPane1.setLayer(S6, javax.swing.JLayeredPane.DEFAULT_LAYER);

		javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(
				jLayeredPane1);
		jLayeredPane1.setLayout(jLayeredPane1Layout);
		jLayeredPane1Layout
				.setHorizontalGroup(jLayeredPane1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jLayeredPane1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jLayeredPane1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jLayeredPane1Layout
																		.createSequentialGroup()
																		.addComponent(
																				S1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				60,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				S2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				60,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				S3,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				60,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jLayeredPane1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jLayeredPane1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								S4,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								60,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								S7,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								60,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGroup(
																				jLayeredPane1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jLayeredPane1Layout
																										.createSequentialGroup()
																										.addGap(12,
																												12,
																												12)
																										.addComponent(
																												S8,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												60,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addComponent(
																												S9,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												60,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGroup(
																								jLayeredPane1Layout
																										.createSequentialGroup()
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addComponent(
																												S5,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												60,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(12,
																												12,
																												12)
																										.addComponent(
																												S6,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												60,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		jLayeredPane1Layout
				.setVerticalGroup(jLayeredPane1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jLayeredPane1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jLayeredPane1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																S1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																60,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																S2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																60,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																S3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																60,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												jLayeredPane1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																S4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																60,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																S5,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																60,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																S6,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																60,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												jLayeredPane1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																S7,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																60,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																S8,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																60,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																S9,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																60,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		getContentPane().add(
				jLayeredPane1,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(429, 156, -1,
						-1));

		jLabel3.setText("Función heurística:");
		getContentPane().add(
				jLabel3,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 435, -1,
						-1));

		jLabel10.setText("f(n) = g(n) + ");
		getContentPane().add(
				jLabel10,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, -1,
						-1));

		pesoAlpha.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				pesoAlphaActionPerformed(evt);
			}
		});
		pesoAlpha.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				pesoAlphaKeyTyped(evt);
			}
		});
		getContentPane().add(
				pesoAlpha,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 43,
						32));

		jLabel11.setText("h(n)");
		getContentPane().add(
				jLabel11,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, -1,
						-1));

		generarArbol1.setText("Generar");
		generarArbol1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				generarArbol1ActionPerformed(evt);
			}
		});
		getContentPane().add(
				generarArbol1,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, -1,
						40));

		opcion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
				"INCORRECTOS", "DIFERENCIA" }));
		opcion.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				opcionActionPerformed(evt);
			}
		});
		getContentPane().add(
				opcion,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 431, -1,
						-1));

		Ptxt.setText("P:");
		getContentPane().add(
				Ptxt,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, -1,
						-1));

		jLabel4.setText("Q:");
		getContentPane().add(
				jLabel4,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, -1,
						-1));

		Pjtext.setEditable(false);
		Pjtext.setEnabled(false);
		Pjtext.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				PjtextActionPerformed(evt);
			}
		});
		getContentPane().add(
				Pjtext,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 50,
						30));

		Qjtext.setEditable(false);
		Qjtext.setEnabled(false);
		Qjtext.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				QjtextActionPerformed(evt);
			}
		});
		getContentPane().add(
				Qjtext,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 456, 50,
						30));

		jLabel5.setText("Camino:");
		getContentPane().add(
				jLabel5,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, -1,
						-1));

		caminojtext.setEditable(false);
		caminojtext.setEnabled(false);
		getContentPane().add(
				caminojtext,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490,
						270, 30));

		arbolbtn.setText("Ver árbol");
		arbolbtn.setEnabled(false);
		arbolbtn.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				arbolbtnActionPerformed(evt);
			}
		});
		getContentPane().add(
				arbolbtn,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 550, -1,
						40));

		etiquetaSol.setEnabled(false);
		getContentPane().add(
				etiquetaSol,
				new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 550,
						150, 20));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void I1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_I1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_I1ActionPerformed

	private void I4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_I4ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_I4ActionPerformed

	private void I7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_I7ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_I7ActionPerformed

	private void I2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_I2ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_I2ActionPerformed

	private void I5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_I5ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_I5ActionPerformed

	private void I8ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_I8ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_I8ActionPerformed

	private void I3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_I3ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_I3ActionPerformed

	private void I9ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_I9ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_I9ActionPerformed

	private void I6ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_I6ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_I6ActionPerformed

	private void S1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_S1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_S1ActionPerformed

	private void S4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_S4ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_S4ActionPerformed

	private void S7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_S7ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_S7ActionPerformed

	private void S2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_S2ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_S2ActionPerformed

	private void S5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_S5ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_S5ActionPerformed

	private void S8ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_S8ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_S8ActionPerformed

	private void S3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_S3ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_S3ActionPerformed

	private void S9ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_S9ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_S9ActionPerformed

	private void S6ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_S6ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_S6ActionPerformed

	private void generarArbol1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_generarArbol1ActionPerformed
		String cadenaInicial, cadenaSol, camino = "", p, q;
		boolean banderaSol = false;
		int P = 0, Q = 0, opcionL = 0;
		float peso = 0.0f;
		char opc;

		if (pesoAlpha.getText().equals(0)) {
			pesoAlpha.setEnabled(false);
			peso = 1.0f;
		} else {
			peso = Float.parseFloat(pesoAlpha.getText());
		}
		if (opcionL == 0)
			opc = 'I';
		else
			opc = 'D';
		cadenaInicial = I1.getText() + " " + I2.getText() + " " + I3.getText()
				+ " " + I4.getText() + " " + I5.getText() + " " + I6.getText()
				+ " " + I7.getText() + " " + I8.getText() + " " + I9.getText();
		cadenaSol = S1.getText() + " " + S2.getText() + " " + S3.getText()
				+ " " + S4.getText() + " " + S5.getText() + " " + S6.getText()
				+ " " + S7.getText() + " " + S8.getText() + " " + S9.getText();
		Puzzle pInicial = new Puzzle(cadenaInicial.replaceAll("x", "X"));
		if (opc == 'I') {
			pInicial.heuristicaIncorrecto();
		} else {
			pInicial.heuristicaDifferencia();
		}
		Puzzle pFinal = new Puzzle(cadenaSol.replaceAll("x", "X"));
		pInicial.solucion(pFinal);
		pInicial.factor(peso);
		ArbolGeneradorPuzzle G = new ArbolGeneradorPuzzle();
		G.generarArbol(pInicial, pFinal);

		Puzzle solucionEncontrada = G.solucion();
		String strCamino = G.stringCamino();
		camino = strCamino;
		Q = G.getQ().size();
		P = G.getP().size();
		this.arbol = G;

		if (solucionEncontrada != null) {
			banderaSol = true;
		}

		if (banderaSol != false) {
			Pjtext.setText("" + P);
			Qjtext.setText("" + Q);
			caminojtext.setText(camino);
			arbolbtn.setEnabled(true);
			etiquetaSol.setEnabled(false);
			etiquetaSol.setText("");
		} else {
			etiquetaSol.setEnabled(true);
			etiquetaSol.setText("¡No hay solución!");
			caminojtext.setText("");
			Pjtext.setText("" + P);
			Qjtext.setText("" + Q);
		}

		System.out.println("Cadena I:  " + cadenaInicial + " cadena Sol "
				+ cadenaSol + " peso :" + peso + " opc " + opc);

	}// GEN-LAST:event_generarArbol1ActionPerformed

	private void opcionActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_opcionActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_opcionActionPerformed

	private void I1KeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_I1KeyTyped
		// TODO add your handling code here:
		if (I1.getText().length() == 1)
			evt.consume();
		char caracter = evt.getKeyChar();

		if (caracter == '0')
			I1.setText("x");
		// Verificar si la tecla pulsada no es un digito
		if (((caracter < '0') || (caracter > '9')) && (caracter != '\b' /*
																		 * corresponde
																		 * a
																		 * BACK_SPACE
																		 */)) {
			evt.consume(); // ignorar el evento de teclado
		}
	}// GEN-LAST:event_I1KeyTyped

	private void I2KeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_I2KeyTyped
		// TODO add your handling code here:
		if (this.I2.getText().length() == 1)
			evt.consume();
		char caracter = evt.getKeyChar();
		if (caracter == '0')
			I2.setText("x");
		// Verificar si la tecla pulsada no es un digito
		if (((caracter < '0') || (caracter > '9')) && (caracter != '\b' /*
																		 * corresponde
																		 * a
																		 * BACK_SPACE
																		 */)) {
			evt.consume(); // ignorar el evento de teclado
		}

	}// GEN-LAST:event_I2KeyTyped

	private void I3KeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_I3KeyTyped
		// TODO add your handling code here:
		if (this.I3.getText().length() == 1)
			evt.consume();
		char caracter = evt.getKeyChar();
		if (caracter == '0')
			I3.setText("x");
		// Verificar si la tecla pulsada no es un digito
		if (((caracter < '0') || (caracter > '9')) && (caracter != '\b' /*
																		 * corresponde
																		 * a
																		 * BACK_SPACE
																		 */)) {
			evt.consume(); // ignorar el evento de teclado
		}
	}// GEN-LAST:event_I3KeyTyped

	private void I4KeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_I4KeyTyped
		// TODO add your handling code here:
		if (this.I4.getText().length() == 1)
			evt.consume();
		char caracter = evt.getKeyChar();
		if (caracter == '0')
			I4.setText("x");
		// Verificar si la tecla pulsada no es un digito
		if (((caracter < '0') || (caracter > '9')) && (caracter != '\b' /*
																		 * corresponde
																		 * a
																		 * BACK_SPACE
																		 */)) {
			evt.consume(); // ignorar el evento de teclado
		}
	}// GEN-LAST:event_I4KeyTyped

	private void I5KeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_I5KeyTyped
		// TODO add your handling code here:
		if (this.I5.getText().length() == 1)
			evt.consume();
		char caracter = evt.getKeyChar();
		if (caracter == '0')
			I5.setText("x");
		// Verificar si la tecla pulsada no es un digito
		if (((caracter < '0') || (caracter > '9')) && (caracter != '\b' /*
																		 * corresponde
																		 * a
																		 * BACK_SPACE
																		 */)) {
			evt.consume(); // ignorar el evento de teclado
		}
	}// GEN-LAST:event_I5KeyTyped

	private void I6KeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_I6KeyTyped
		// TODO add your handling code here:
		if (this.I6.getText().length() == 1)
			evt.consume();
		char caracter = evt.getKeyChar();
		if (caracter == '0')
			I6.setText("x");
		// Verificar si la tecla pulsada no es un digito
		if (((caracter < '0') || (caracter > '9')) && (caracter != '\b' /*
																		 * corresponde
																		 * a
																		 * BACK_SPACE
																		 */)) {
			evt.consume(); // ignorar el evento de teclado
		}
	}// GEN-LAST:event_I6KeyTyped

	private void I7KeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_I7KeyTyped
		// TODO add your handling code here:
		if (this.I7.getText().length() == 1)
			evt.consume();
		char caracter = evt.getKeyChar();
		if (caracter == '0')
			I7.setText("x");
		// Verificar si la tecla pulsada no es un digito
		if (((caracter < '0') || (caracter > '9')) && (caracter != '\b' /*
																		 * corresponde
																		 * a
																		 * BACK_SPACE
																		 */)) {
			evt.consume(); // ignorar el evento de teclado
		}
	}// GEN-LAST:event_I7KeyTyped

	private void I8KeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_I8KeyTyped
		// TODO add your handling code here:

		if (I8.getText().length() == 1)
			evt.consume();
		char caracter = evt.getKeyChar();
		if (caracter == '0')
			I8.setText("x");
		// Verificar si la tecla pulsada no es un digito
		if (((caracter < '0') || (caracter > '9')) && (caracter != '\b' /*
																		 * corresponde
																		 * a
																		 * BACK_SPACE
																		 */)) {
			evt.consume(); // ignorar el evento de teclado
		}
	}// GEN-LAST:event_I8KeyTyped

	private void I9KeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_I9KeyTyped
		// TODO add your handling code here:
		if (this.I9.getText().length() == 1)
			evt.consume();
		char caracter = evt.getKeyChar();
		if (caracter == '0')
			I9.setText("x");
		// Verificar si la tecla pulsada no es un digito
		if (((caracter < '0') || (caracter > '9')) && (caracter != '\b' /*
																		 * corresponde
																		 * a
																		 * BACK_SPACE
																		 */)) {
			evt.consume(); // ignorar el evento de teclado
		}
	}// GEN-LAST:event_I9KeyTyped

	private void S1KeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_S1KeyTyped
		// TODO add your handling code here:
		if (this.S1.getText().length() == 1)
			evt.consume();
		char caracter = evt.getKeyChar();
		if (caracter == '0')
			S1.setText("x");
		// Verificar si la tecla pulsada no es un digito
		if (((caracter < '0') || (caracter > '9')) && (caracter != '\b' /*
																		 * corresponde
																		 * a
																		 * BACK_SPACE
																		 */)) {
			evt.consume(); // ignorar el evento de teclado
		}
	}// GEN-LAST:event_S1KeyTyped

	private void pesoAlphaKeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_pesoAlphaKeyTyped
		// TODO add your handling code here:
		char caracter = evt.getKeyChar();

		if (((caracter < '0') || (caracter > '9'))
				&& (caracter != evt.VK_BACK_SPACE) && (caracter != '.')) {
			/*
			 * lo que deseo colocar aqui es si ya se pulso el caracter (.) el
			 * mismo no se pueda repetir
			 */
			evt.consume();
		}

	}// GEN-LAST:event_pesoAlphaKeyTyped

	private void QjtextActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_QjtextActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_QjtextActionPerformed

	private void pesoAlphaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pesoAlphaActionPerformed
		// TODO add your handling code here:

	}// GEN-LAST:event_pesoAlphaActionPerformed

	private void PjtextActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_PjtextActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_PjtextActionPerformed

	private void arbolbtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_arbolbtnActionPerformed
		// TODO add your handling code here:

		// Llamar a función que genera árbol

		if (this.arbol.solucion() != null) {
			ArbolPuzzleGraph apg = new ArbolPuzzleGraph(this.arbol);
//			apg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
			apg.setSize(1024, 768);
			apg.setVisible(true);
		}

	}// GEN-LAST:event_arbolbtnActionPerformed

	private void S2KeyTyped(java.awt.event.KeyEvent evt) {
		// TODO add your handling code here:
		if (this.S2.getText().length() == 1)
			evt.consume();
		char caracter = evt.getKeyChar();
		if (caracter == '0')
			S2.setText("x");
		// Verificar si la tecla pulsada no es un digito
		if (((caracter < '0') || (caracter > '9')) && (caracter != '\b' /*
																		 * corresponde
																		 * a
																		 * BACK_SPACE
																		 */)) {
			evt.consume(); // ignorar el evento de teclado
		}
	}

	private void S3KeyTyped(java.awt.event.KeyEvent evt) {
		// TODO add your handling code here:
		if (this.S3.getText().length() == 1)
			evt.consume();
		char caracter = evt.getKeyChar();
		if (caracter == '0')
			S3.setText("x");
		// Verificar si la tecla pulsada no es un digito
		if (((caracter < '0') || (caracter > '9')) && (caracter != '\b' /*
																		 * corresponde
																		 * a
																		 * BACK_SPACE
																		 */)) {
			evt.consume(); // ignorar el evento de teclado
		}
	}

	private void S4KeyTyped(java.awt.event.KeyEvent evt) {
		// TODO add your handling code here:
		if (this.S4.getText().length() == 1)
			evt.consume();
		char caracter = evt.getKeyChar();
		if (caracter == '0')
			S4.setText("x");
		// Verificar si la tecla pulsada no es un digito
		if (((caracter < '0') || (caracter > '9')) && (caracter != '\b' /*
																		 * corresponde
																		 * a
																		 * BACK_SPACE
																		 */)) {
			evt.consume(); // ignorar el evento de teclado
		}
	}

	private void S5KeyTyped(java.awt.event.KeyEvent evt) {
		// TODO add your handling code here:
		if (this.S5.getText().length() == 1)
			evt.consume();
		char caracter = evt.getKeyChar();
		if (caracter == '0')
			S5.setText("x");
		// Verificar si la tecla pulsada no es un digito
		if (((caracter < '0') || (caracter > '9')) && (caracter != '\b' /*
																		 * corresponde
																		 * a
																		 * BACK_SPACE
																		 */)) {
			evt.consume(); // ignorar el evento de teclado
		}
	}

	private void S6KeyTyped(java.awt.event.KeyEvent evt) {
		// TODO add your handling code here:
		if (this.S6.getText().length() == 1)
			evt.consume();
		char caracter = evt.getKeyChar();
		if (caracter == '0')
			S6.setText("x");
		// Verificar si la tecla pulsada no es un digito
		if (((caracter < '0') || (caracter > '9')) && (caracter != '\b' /*
																		 * corresponde
																		 * a
																		 * BACK_SPACE
																		 */)) {
			evt.consume(); // ignorar el evento de teclado
		}
	}

	private void S7KeyTyped(java.awt.event.KeyEvent evt) {
		// TODO add your handling code here:
		if (this.S7.getText().length() == 1)
			evt.consume();
		char caracter = evt.getKeyChar();
		if (caracter == '0')
			S7.setText("x");
		// Verificar si la tecla pulsada no es un digito
		if (((caracter < '0') || (caracter > '9')) && (caracter != '\b' /*
																		 * corresponde
																		 * a
																		 * BACK_SPACE
																		 */)) {
			evt.consume(); // ignorar el evento de teclado
		}
	}

	private void S8KeyTyped(java.awt.event.KeyEvent evt) {
		// TODO add your handling code here:
		if (this.S8.getText().length() == 1)
			evt.consume();
		char caracter = evt.getKeyChar();
		if (caracter == '0')
			S8.setText("x");
		// Verificar si la tecla pulsada no es un digito
		if (((caracter < '0') || (caracter > '9')) && (caracter != '\b' /*
																		 * corresponde
																		 * a
																		 * BACK_SPACE
																		 */)) {
			evt.consume(); // ignorar el evento de teclado
		}
	}

	private void S9KeyTyped(java.awt.event.KeyEvent evt) {
		// TODO add your handling code here:
		if (this.S9.getText().length() == 1)
			evt.consume();
		char caracter = evt.getKeyChar();
		if (caracter == '0')
			S9.setText("x");
		// Verificar si la tecla pulsada no es un digito
		if (((caracter < '0') || (caracter > '9')) && (caracter != '\b' /*
																		 * corresponde
																		 * a
																		 * BACK_SPACE
																		 */)) {
			evt.consume(); // ignorar el evento de teclado
		}
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(GUI_Puzzle.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(GUI_Puzzle.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(GUI_Puzzle.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(GUI_Puzzle.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new GUI_Puzzle().setVisible(true);
			}
		});

	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTextField I1;
	private javax.swing.JTextField I2;
	private javax.swing.JTextField I3;
	private javax.swing.JTextField I4;
	private javax.swing.JTextField I5;
	private javax.swing.JTextField I6;
	private javax.swing.JTextField I7;
	private javax.swing.JTextField I8;
	private javax.swing.JTextField I9;
	private javax.swing.JTextField Pjtext;
	private javax.swing.JLabel Ptxt;
	private javax.swing.JTextField Qjtext;
	private javax.swing.JTextField S1;
	private javax.swing.JTextField S2;
	private javax.swing.JTextField S3;
	private javax.swing.JTextField S4;
	private javax.swing.JTextField S5;
	private javax.swing.JTextField S6;
	private javax.swing.JTextField S7;
	private javax.swing.JTextField S8;
	private javax.swing.JTextField S9;
	private javax.swing.JButton arbolbtn;
	private javax.swing.JTextField caminojtext;
	private javax.swing.JLabel etiquetaSol;
	private javax.swing.JButton generarArbol1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JLayeredPane jLayeredPane1;
	private javax.swing.JLayeredPane jLayeredPane2;
	private javax.swing.JComboBox<String> opcion;
	private javax.swing.JTextField pesoAlpha;
	// End of variables declaration//GEN-END:variables
}
